name: Create Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Create archive
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: zip mpv-cut.zip main.lua make_cuts.js

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.tag_version.outputs.new_tag
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            mpv-cut.zip
          fail_on_unmatched_files: true
