name: Create Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Create directory structure
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir -p tmp/scripts
          mkdir -p tmp/script-opts
          cp mpv-lossless-cut.lua tmp/scripts/
          cp mpv-lossless-cut.conf tmp/script-opts/

      - name: Create archive
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd tmp
          zip -r ../mpv-lossless-cut.zip scripts script-opts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mpv-lossless-cut.zip
          fail_on_unmatched_files: true
